#!/usr/bin/env python3
"""Generate part 1 of the expanded deployment SRE document."""
import os

target = os.path.join(os.path.dirname(__file__), "01-学习文档.md")
buf = []
def w(s=""):
    buf.append(s)
def sep():
    w("")

w("# E13 前端部署与运维（SRE）")
sep()
w("> 目标：掌握前端应用的部署、发布、监控、容灾和容量管理，保障线上服务稳定可用。")
sep()
w("---")
sep()
w("## 核心要点（TL;DR）")
sep()
w("- 前端部署不只是把文件上传到 CDN，还包括缓存策略、回滚、灰度和可观测性。")
w("- SRE 的核心是用工程化手段提升系统可靠性，而不是靠人力值守。")
w("- 发布策略决定风险：全量、灰度、蓝绿、金丝雀、A/B 测试各有适用场景。")
w("- 可观测性三大支柱：日志、指标、链路追踪。")
w("- 容灾和回滚能力比发布速度更重要。")
sep()
w("---")
sep()
w("## 1. 前端部署基础")
sep()
w("### 1.1 部署流程")
sep()
w("```")
w("构建产物 -> 静态资源上传 -> CDN 刷新 -> DNS/路由切换 -> 验证 -> 监控")
w("```")
sep()
w("### 1.2 静态资源托管")
sep()
w("- **对象存储**：OSS/S3/MinIO")
w("- **CDN**：加速静态资源分发")
w("- **边缘节点**：Cloudflare、Vercel Edge、AWS CloudFront")
sep()
w("### 1.3 缓存策略")
sep()
w("| 资源类型 | 缓存策略 | 说明 |")
w("|----------|---------|------|")
w("| HTML | no-cache / 短缓存 | 保证最新入口 |")
w("| JS/CSS（带 hash） | 长期缓存 | 文件名变化自动失效 |")
w("| 图片/字体 | 长期缓存 | 不常变化 |")
sep()
w("### 1.4 对象存储与 CDN 配置示例（OSS + CDN）")
sep()
w("```yaml")
w("# 阿里云 OSS 静态网站托管配置")
w("Bucket:")
w("  Name: my-app-prod")
w("  Access: public-read")
w("  StaticWebsite:")
w("    Index: index.html")
w("    Error: index.html          # SPA 路由兜底")
w("  Lifecycle:")
w("    - prefix: builds/")
w("      expire_days: 90          # 历史构建版本自动清理")
w("")
w("CDN:")
w("  Domain: static.example.com")
w("  Origin: my-app-prod.oss-cn-hangzhou.aliyuncs.com")
w("  CacheRules:")
w("    - pattern: *.html")
w("      TTL: 0                   # no-cache")
w("    - pattern: *.js,*.css")
w("      TTL: 365d                # hash 文件名，长期缓存")
w("    - pattern: *.png,*.jpg,*.svg,*.woff2")
w("      TTL: 365d")
w("  Preload:")
w("    enabled: true              # 每次部署后预热热门资源")
w("```")
sep()
w("### 1.5 SPA 路由历史模式下的 Nginx 配置")
sep()
w("```nginx")
w("server {")
w("    listen 80;")
w("    server_name example.com;")
w("    root /usr/share/nginx/html;")
w("")
w("    gzip on;")
w("    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;")
w("    gzip_min_length 1024;")
w("    gzip_static on;")
w("")
w("    location ~* \\.(?:css|js|woff2?|svg|png|jpg|jpeg|gif|ico|webp)$ {")
w("        expires 1y;")
w("        add_header Cache-Control \"public, immutable\";")
w("        access_log off;")
w("    }")
w("")
w("    location ~* \\.html$ {")
w("        expires -1;")
w("        add_header Cache-Control \"no-cache, no-store, must-revalidate\";")
w("    }")
w("")
w("    # SPA 路由历史模式：所有非文件请求返回 index.html")
w("    location / {")
w("        try_files $uri $uri/ /index.html;")
w("    }")
w("")
w("    # 安全头")
w("    add_header X-Frame-Options DENY;")
w("    add_header X-Content-Type-Options nosniff;")
w("    add_header X-XSS-Protection \"1; mode=block\";")
w("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\";")
w("}")
w("```")
sep()
w("### 1.6 .dockerignore 最佳实践")
sep()
w("```dockerignore")
w("node_modules")
w(".git")
w(".gitignore")
w".DS_Store"
w"*.md"
w"src/"
w".env"
w".env.local"
w".editorconfig"
w".eslintrc*"
w".prettierrc*"
w"tsconfig.json"
w"tests/"
w"e2e/"
w"__tests__/"
w"coverage/"
w"```")
sep()
w("### 1.7 Docker 多阶段构建前端镜像")
sep()
w("```dockerfile")
w("# ---- 阶段一：构建 ----")
w("FROM node:20-alpine AS builder")
w("WORKDIR /app")
w("")
w("COPY package.json pnpm-lock.yaml ./")
w("RUN corepack enable && pnpm install --frozen-lockfile")
w("")
w("COPY . .")
w("ARG APP_ENV=production")
w("RUN echo \"VITE_APP_ENV=${APP_ENV}\" >> .env.production")
w("RUN npm run build")
w("")
w("# ---- 阶段二：运行 ----")
w("FROM nginx:1.25-alpine")
w("RUN rm -rf /etc/nginx/conf.d/default.conf")
w("COPY nginx.conf /etc/nginx/conf.d/")
w("COPY --from=builder /app/dist /usr/share/nginx/html")
w("")
w("# 健康检查")
w("HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\")
w("  CMD wget --no-verbose --tries=1 --spider http://localhost/ || exit 1")
w("")
w("EXPOSE 80")
w("CMD [\"nginx\", \"-g\", \"daemon off;\"]")
w("```")
sep()
w("### 1.8 Docker Compose 本地验证")
sep()
w("```yaml")
w("version: \"3.8\"")
w("services:")
w("  app:")
w("    build:")
w("      context: .")
w("      args:")
w("        APP_ENV: staging")
w("    ports:")
w("      - \"8080:80\"")
w"    healthcheck:")
w("      test: [\"CMD\", \"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost/\"]")
w("      interval: 30s")
w("      timeout: 3s")
w("      retries: 3")
w"```")
sep()
w("## 2. 发布策略详解")
sep()
w("### 2.1 策略对比总览")
sep()
w("| 策略 | 速度 | 风险 | 成本 | 回滚速度 | 适用场景 |")
w("|------|------|------|------|---------|---------|")
w("| 全量发布 | 快 | 高 | 低 | 中等 | 热修复、低风险变更 |")
w("| 灰度发布 | 慢 | 中 | 低 | 快 | 功能逐步开放 |")
w("| 金丝雀发布 | 中等 | 低 | 中 | 快 | 重大版本发布 |")
w("| 蓝绿发布 | 快 | 极低 | 高 | 极快 | 核心服务、支付等关键系统 |")
w("| A/B 测试 | 慢 | 低 | 中 | N/A | 业务验证、UI 实验 |")
w("| 滚动发布 | 中等 | 中 | 低 | 慢 | 后端微服务，前端少用 |")
sep()
w("### 2.2 蓝绿发布（Blue-Green Deploy）")
sep()
w("**原理**：准备两套完全独立的、与生产环境镜像的环境。")
w("蓝环境（当前生产）和绿环境（新版本）同时运行，通过路由/负载均衡器切换流量。")
sep()
w("**拓扑示意**：")
w("```")
w("                   ┌──────────────┐")
w("                   │  Load Balancer │")
w("                   │  (Router/Nginx)│")
w("                   └──────┬───────┘")
w("                          │")
w("              ┌───────────┴───────────┐")
w("              │                       │")
w("       ┌──────▼──────┐       ┌──────▼──────┐")
w("       │  Blue (v1)  │       │ Green (v2)  │")
w("       │  (current)  │       │  (staging)  │")
w"       └──────────────┘       └──────────────┘")
sep()
w("**步骤**：")
w("1. 部署 v2 到绿环境，完整 CI/CD 流程一次性完成")
w("2. 在绿环境运行集成测试和烟雾测试")
w("3. 切换负载均衡器，将 100% 流量导向绿环境")
w("4. 监控 15-30 分钟，观察错误率和性能指标")
w("5. 如有问题，立即切回蓝环境（秒级回滚）")
w("6. 确认稳定后，蓝环境保留作为下一次回滚目标")
sep()
w("**优点**：回滚极快（DNS/路由切换即可）、零停机、环境隔离彻底")
w("**缺点**：资源成本翻倍、DB 兼容性需要额外关注、切换瞬间可能有短暂不一致")
sep()
print("Content written to:", target)
